### ISSUE TITLE
comments can't be highlighted correctly inside of a table

### ISSUE THREAD

**Issue by msdpotato3** [Vurv78/Expression-LS#10]
using the extensions version: 1.1.0

Expected behavior: comments appears as gray

Actual behavior: comments inside of a table will appear as unrecognized

code to reproduce the bug:

```
PST = table(
    "session" = table(
        "sessionname" = "autoload"
        "history" = table(),
        "queue" = table(),
        "playlists" = table(),
        "settings" = table(
            "queueindex" = 1, ## 1~n
            "historyindex" = 0, ## 0~-n
            ## listOnce, listLoop, singleLoop, randomLoop
            "playmode" = "list",
            "volume" = 1,
            "range" = 1000,
            "isplaying" = 0
        )
    )
)
```
screenshot:
![image](https://github.com/Vurv78/Expression-LS/assets/91935401/3bff523a-0d3f-488c-bb6c-9e45a805fd7a)

**Comment by vurvdev** [comment]
Fixed by https://github.com/Vurv78/Expression-LS/commit/5bb4847e07e727d40790f1418a8e08eb445f95ab
