### ISSUE TITLE
escaped double quote will make a open quote

### ISSUE THREAD

**Issue by msdpotato3** [Vurv78/Expression-LS#11]

**Comment by vurvdev** [comment]
Fixed by https://github.com/Vurv78/Expression-LS/commit/01e5b2066cbad671b865a48b1c8f7f488b29ab33

**Comment by msdpotato3** [comment]
also a few more bugs like function return type and function like format() will match keyword "for"
![image](https://github.com/Vurv78/Expression-LS/assets/91935401/0faeb5f4-1fc2-4146-96cb-3d51f5a586f1)

**Comment by vurvdev** [comment]
Fixed
